INCLUDE = [
    "gnome_menu_common",
    "apt_update_upgrade",
    "apt_installs",
    "apt_removes",
    "gnome_debloat",
    "install_chrome",
    "install_docker",
    "install_vscode",
    "flatpak_install",
    "gnome_enhancements",
    "add_jetbrains_fonts",
    "gnome_extensions",
    "gnome_manage_menu_folders",
    "gnome_tidy_menu",
]
